# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Transportation And Education Facilities - KGE2023
email: thomas.pasquali@studenti.unitn.it
description: > # this means to ignore newlines until "baseurl:"
  TODO
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://thomaspasquali.github.io/TransportationAndEducationFacilities_KGE2023/" # the base hostname & protocol for your site
twitter_username: NONE 
github_username: thomas.pasquali

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->